version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app/static/uploads:/app/static/uploads:rw
      - ./app/static/features:/app/static/features:ro
      - ./app/static/results:/app/static/results:rw
      - ./data:/app/data:ro
      - db_data:/app/db_data
    environment:
      - SECRET_KEY=${SECRET_KEY:-changez-moi-en-production}
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///db_data/secure_users.db
      - MAX_CONTENT_LENGTH=10485760
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - app-network

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge
